In [1]:
import numpy as numpy
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
data = pd.read_csv("Coursera.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Coursera.csv'

In [ ]:
data.head()

,Course Name,University,Difficulty Level,Course Rating,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Michigan State University,Beginner,4.8,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Coursera Project Network,Beginner,4.8,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,�cole Polytechnique,Advanced,4.1,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,IESE Business School,Intermediate,4.8,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Coursera Project Network,Beginner,4.6,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...

In [ ]:
data.shape

(3522, 7)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3522 entries, 0 to 3521
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Course Name         3522 non-null   object
 1   University          3522 non-null   object
 2   Difficulty Level    3522 non-null   object
 3   Course Rating       3522 non-null   object
 4   Course URL          3522 non-null   object
 5   Course Description  3522 non-null   object
 6   Skills              3522 non-null   object
dtypes: object(7)
memory usage: 192.7+ KB

In [ ]:
data.isnull().sum()

Course Name           0
University            0
Difficulty Level      0
Course Rating         0
Course URL            0
Course Description    0
Skills                0
dtype: int64

In [ ]:
data["Difficulty Level"].value_counts()

Difficulty Level
Beginner          1444
Advanced          1005
Intermediate       837
Conversant         186
Not Calibrated      50
Name: count, dtype: int64

In [ ]:
data["Course Rating"].value_counts()

Course Rating
4.7               740
4.6               623
4.8               598
4.5               389
4.4               242
4.9               180
4.3               165
4.2               121
5                  90
4.1                85
Not Calibrated     82
4                  51
3.8                24
3.9                20
3.6                18
3.7                18
3.5                17
3.4                13
3                  12
3.2                 9
3.3                 6
2.9                 6
2.6                 2
2.8                 2
2.4                 2
1                   2
2                   1
2.5                 1
3.1                 1
1.9                 1
2.3                 1
Name: count, dtype: int64

In [ ]:
data["University"].value_counts()

University
Coursera Project Network                      562
University of Illinois at Urbana-Champaign    138
Johns Hopkins University                      110
University of Colorado Boulder                101
University of Michigan                        101
                                             ...
University of Nebraska                          1
Pontificia Universidad Cat�lica de Chile        1
VMware                                          1
E-Learning Development Fund                     1
The World Bank Group                            1
Name: count, Length: 184, dtype: int64

In [ ]:
data["Course Name"].value_counts()

Course Name
Google Cloud Platform Fundamentals: Core Infrastructure         8
Data Visualization with Python                                  4
The Art of Music Production                                     4
Python for Data Science and AI                                  4
What is Data Science?                                           4
                                                               ..
Recommendation Systems with TensorFlow on GCP                   1
The Changing Arctic                                             1
COVID-19 - A clinical update                                    1
How to Create Text Effects in GIMP                              1
Building Test Automation Framework using Selenium and TestNG    1
Name: count, Length: 3416, dtype: int64

In [ ]:
data.columns

Index(['Course Name', 'University', 'Difficulty Level', 'Course Rating',
       'Course URL', 'Course Description', 'Skills'],
      dtype='object')

In [ ]:
data = data[['Course Name','Difficulty Level','Course URL','Course Description','Skills']]

In [ ]:
data.head()

,Course Name,Difficulty Level,Course URL,Course Description,Skills
0,Write A Feature Length Screenplay For Film Or ...,Beginner,https://www.coursera.org/learn/write-a-feature...,Write a Full Length Feature Film Script In th...,Drama Comedy peering screenwriting film D...
1,Business Strategy: Business Model Canvas Analy...,Beginner,https://www.coursera.org/learn/canvas-analysis...,"By the end of this guided project, you will be...",Finance business plan persona (user experien...
2,Silicon Thin Film Solar Cells,Advanced,https://www.coursera.org/learn/silicon-thin-fi...,This course consists of a general presentation...,chemistry physics Solar Energy film lambda...
3,Finance for Managers,Intermediate,https://www.coursera.org/learn/operational-fin...,"When it comes to numbers, there is always more...",accounts receivable dupont analysis analysis...
4,Retrieve Data using Single-Table SQL Queries,Beginner,https://www.coursera.org/learn/single-table-sq...,In this course you�ll learn how to effectively...,Data Analysis select (sql) database manageme...

In [ ]:
data = data.copy()

data["Course Name"] = (
    data["Course Name"]
    .str.replace(" ", "", regex=False)
    .str.replace(":", "", regex=False)
    .str.replace(r",{2,}", ",", regex=True)
)

data["Course Description"] = (
    data["Course Description"]
    .str.replace(r"[ :_()]", "", regex=True)
    .str.replace(r",{2,}", ",", regex=True)
)

data["Skills"] = (
    data["Skills"]
    .str.replace(r"[()]", "", regex=True)
)

In [ ]:
data.head()

,Course Name,Difficulty Level,Course URL,Course Description,Skills
0,WriteAFeatureLengthScreenplayForFilmOrTelevision,Beginner,https://www.coursera.org/learn/write-a-feature...,"WriteaFullLengthFeatureFilmScriptInthiscourse,...",Drama Comedy peering screenwriting film D...
1,BusinessStrategyBusinessModelCanvasAnalysiswit...,Beginner,https://www.coursera.org/learn/canvas-analysis...,"Bytheendofthisguidedproject,youwillbefluentini...",Finance business plan persona user experienc...
2,SiliconThinFilmSolarCells,Advanced,https://www.coursera.org/learn/silicon-thin-fi...,Thiscourseconsistsofageneralpresentationofsola...,chemistry physics Solar Energy film lambda...
3,FinanceforManagers,Intermediate,https://www.coursera.org/learn/operational-fin...,"Whenitcomestonumbers,thereisalwaysmorethanmeet...",accounts receivable dupont analysis analysis...
4,RetrieveDatausingSingle-TableSQLQueries,Beginner,https://www.coursera.org/learn/single-table-sq...,Inthiscourseyou�lllearnhowtoeffectivelyretriev...,Data Analysis select sql database management...

In [ ]:
data['tags'] = data['Course Name'] + data['Difficulty Level'] + data['Course Description'] + data['Skills']

In [ ]:
data.head()

,Course Name,Difficulty Level,Course URL,Course Description,Skills,tags
0,WriteAFeatureLengthScreenplayForFilmOrTelevision,Beginner,https://www.coursera.org/learn/write-a-feature...,"WriteaFullLengthFeatureFilmScriptInthiscourse,...",Drama Comedy peering screenwriting film D...,WriteAFeatureLengthScreenplayForFilmOrTelevisi...
1,BusinessStrategyBusinessModelCanvasAnalysiswit...,Beginner,https://www.coursera.org/learn/canvas-analysis...,"Bytheendofthisguidedproject,youwillbefluentini...",Finance business plan persona user experienc...,BusinessStrategyBusinessModelCanvasAnalysiswit...
2,SiliconThinFilmSolarCells,Advanced,https://www.coursera.org/learn/silicon-thin-fi...,Thiscourseconsistsofageneralpresentationofsola...,chemistry physics Solar Energy film lambda...,SiliconThinFilmSolarCellsAdvancedThiscoursecon...
3,FinanceforManagers,Intermediate,https://www.coursera.org/learn/operational-fin...,"Whenitcomestonumbers,thereisalwaysmorethanmeet...",accounts receivable dupont analysis analysis...,FinanceforManagersIntermediateWhenitcomestonum...
4,RetrieveDatausingSingle-TableSQLQueries,Beginner,https://www.coursera.org/learn/single-table-sq...,Inthiscourseyou�lllearnhowtoeffectivelyretriev...,Data Analysis select sql database management...,RetrieveDatausingSingle-TableSQLQueriesBeginne...

In [ ]:
data['tags'].iloc[0] # value at integer 0

'WriteAFeatureLengthScreenplayForFilmOrTelevisionBeginnerWriteaFullLengthFeatureFilmScriptInthiscourse,youwillwriteacomplete,feature-lengthscreenplayforfilmortelevision,beitaseriousdramaorromanticcomedyoranythinginbetween.You�lllearntobreakdownthecreativeprocessintocomponents,andyou�lldiscoverastructuredprocessthatallowsyoutoproduceapolishedandpitch-readyscriptbytheendofthecourse.Completingthisprojectwillincreaseyourconfidenceinyourideasandabilities,andyou�llfeelpreparedtopitchyourfirstscriptandgetstartedonyournext.Thisisacoursedesignedtotapintoyourcreativityandisbasedin"ActiveLearning".Mostoftheactuallearningtakesplacewithinyourownactivities-thatis,writing!Youwilllearnbydoing.HereisalinktoaTRAILERforthecourse.Toviewthetrailer,pleasecopyandpastethelinkintoyourbrowser.https//vimeo.com/382067900/b78b800dc0Learnerreview"LovetheapproachProfessorWheelertakestowardsthiscourse.It\'stothepoint,easytofollow,andveryinformative!WoulddefinitelyrecommendittoanyonewhoisinterestedintakingaScreenplayWritingcourse!ThecoursecurriculumissimpleWewilladoptaprofessionalwritersroomprocessinwhichyou�llwrite,postyourworkforpeerreview,sharefeedbackwithyourpeersandreviseyourworkwiththefeedbackyoureceivefromyourpeers.That\'showwedoitintherealworld.Youwillfeelasifyouwereinaprofessionalwritersroomyetnopriorexperienceasawriterisrequired.I\'maproponentofExperientialLearningActiveLearning.Mylecturesareshortsometimesjusttwominuteslongandtothepoint,designedinastep-by-stepprocessessentialtoyoursuccessasascriptwriter.IwillguideyoubutIwon�t"show"youhowtowrite.Ifirmlybelievethattheonlywaytobecomeawriteristowrite,write,write.LearnerReview"Iwouldliketothankthiscourseinstructor.It\'sanamazingcourse"Whatyou�llneedtogetstartedAsmentionedabove,nopriorscriptwritingexperienceisrequired.Tobeginwith,anybasicwordprocessorwilldo.Duringweektwo,youcanchoosetodownloadsomefreescriptwritingsoftwaresuchasCeltxorTrelbyoryoumaychoosetopurchaseFinalDraft,theindustrystandard,oryoucancontinuetouseyourwordprocessoranddoyourownscriptformatting.LearnerReview"NowIamawriter!"Ifyouhaveanyconcernsregardingtheprotectionofyouroriginalwork,Coursera\'sprivacypolicyprotectsthelearner\'sIPandyouareindeedthesoleownersofyourwork.Drama  Comedy  peering  screenwriting  film  Document Review  dialogue  creative writing  Writing  unix shells arts-and-humanities music-and-art'

In [ ]:
new_df = data[["Course Name", "Course URL", "tags"]].copy()

new_df["Course Name"] = (
    new_df["Course Name"]
    .str.replace(",", " ", regex=False)
)

new_df.rename(
    columns={
        "Course Name": "course_name",
        "Course URL": "course_url"
    },
    inplace=True  # Apply the change directly to the existing DataFrame
)

In [ ]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [ ]:
new_df.head()

,course_name,course_url,tags
0,WriteAFeatureLengthScreenplayForFilmOrTelevision,https://www.coursera.org/learn/write-a-feature...,writeafeaturelengthscreenplayforfilmortelevisi...
1,BusinessStrategyBusinessModelCanvasAnalysiswit...,https://www.coursera.org/learn/canvas-analysis...,businessstrategybusinessmodelcanvasanalysiswit...
2,SiliconThinFilmSolarCells,https://www.coursera.org/learn/silicon-thin-fi...,siliconthinfilmsolarcellsadvancedthiscoursecon...
3,FinanceforManagers,https://www.coursera.org/learn/operational-fin...,financeformanagersintermediatewhenitcomestonum...
4,RetrieveDatausingSingle-TableSQLQueries,https://www.coursera.org/learn/single-table-sq...,retrievedatausingsingle-tablesqlqueriesbeginne...

In [ ]:
new_df.shape

(3522, 3)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_features = 5000, stop_words='english')

In [ ]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [ ]:
import nltk
from nltk.stem.porter import PorterStemmer

In [ ]:
ps = PorterStemmer()

In [ ]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)  #stem

In [ ]:
new_df['tags'] = new_df['tags'].apply(stem)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(vectors)

In [ ]:
def recommend(course):
    course_index = new_df[new_df['course_name'] == course].index[0]
    distance = similarity[course_index]
    course_list = sorted(list(enumerate(distance)), reverse = True, key = lambda x:x[1])[1:7]
    
    recommended_courses = []
    for i in course_list:
        course_name = new_df.iloc[i[0]].course_name
        course_url = new_df.iloc[i[0]].course_url
        recommended_courses.append({'name': course_name, 'url': course_url})
    return recommended_courses

In [ ]:
new_df.head()

,course_name,course_url,tags
0,WriteAFeatureLengthScreenplayForFilmOrTelevision,https://www.coursera.org/learn/write-a-feature...,writeafeaturelengthscreenplayforfilmortelevisi...
1,BusinessStrategyBusinessModelCanvasAnalysiswit...,https://www.coursera.org/learn/canvas-analysis...,businessstrategybusinessmodelcanvasanalysiswit...
2,SiliconThinFilmSolarCells,https://www.coursera.org/learn/silicon-thin-fi...,siliconthinfilmsolarcellsadvancedthiscoursecon...
3,FinanceforManagers,https://www.coursera.org/learn/operational-fin...,financeformanagersintermediatewhenitcomestonum...
4,RetrieveDatausingSingle-TableSQLQueries,https://www.coursera.org/learn/single-table-sq...,retrievedatausingsingle-tablesqlqueriesbeginne...

In [ ]:
recommend("WriteAFeatureLengthScreenplayForFilmOrTelevision")

[{'name': 'ScriptWritingWriteaPilotEpisodeforaTVorWebSeries(Project-CenteredCourse)',
  'url': 'https://www.coursera.org/learn/script-writing'},
 {'name': 'WriteYourFirstNovel',
  'url': 'https://www.coursera.org/learn/write-your-first-novel'},
 {'name': 'TransmediaWriting',
  'url': 'https://www.coursera.org/learn/transmedia-writing'},
 {'name': 'CreativeWritingTheCraftofStyle',
  'url': 'https://www.coursera.org/learn/craft-of-style'},
 {'name': 'CreativeWritingTheCraftofSettingandDescription',
  'url': 'https://www.coursera.org/learn/craft-of-setting-and-description'},
 {'name': 'WritingaPersonalEssay',
  'url': 'https://www.coursera.org/learn/personal-essay'}]

In [ ]:
import pickle

In [ ]:
import os
import pickle

os.makedirs("models", exist_ok=True)

with open("models/similarity.pkl", "wb") as f:
    pickle.dump(similarity, f)

with open("models/courses.pkl", "wb") as f:
    pickle.dump(new_df[['course_name', 'course_url']], f)

print("Files saved successfully!")

Files saved successfully!